# Generated by Django 5.2.17 on 2026-08-31 05:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "owner",
                    models.CharField(help_text="Host display name", max_length=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "quizzes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("text", models.TextField()),
                ("time_limit_seconds", models.IntegerField(default=30)),
                ("order", models.IntegerField(default=0)),
                (
                    "branch_condition",
                    models.JSONField(
                        blank=True,
                        help_text='Condition to select this branch, e.g. {"if_misconception_tag": "sign_error", "threshold_pct": 40}',
                        null=True,
                    ),
                ),
                (
                    "branch_parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent question that branches to this one",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="branches",
                        to="quiz.question",
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="quiz.quiz",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Option",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("text", models.CharField(max_length=500)),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "misconception_tag",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable misconception label for wrong answers",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="quiz.question",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=6, unique=True)),
                (
                    "host",
                    models.CharField(help_text="Host display name", max_length=100),
                ),
                (
                    "host_token",
                    models.UUIDField(default=uuid.uuid4, help_text="Host auth token"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("lobby", "Lobby"),
                            ("live", "Live"),
                            ("paused", "Paused"),
                            ("ended", "Ended"),
                        ],
                        default="lobby",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "current_question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="quiz.question",
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="quiz.quiz",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("display_name", models.CharField(max_length=100)),
                ("session_token", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("is_ghost", models.BooleanField(default=False)),
                (
                    "signal_tokens",
                    models.IntegerField(
                        default=3, help_text="Remaining silent lifeline tokens"
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="quiz.room",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DebriefReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("narrative_text", models.TextField(blank=True)),
                ("suggested_questions", models.JSONField(blank=True, default=list)),
                ("cluster_summary", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "room",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="debrief",
                        to="quiz.room",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuizEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("question_shown", "Question Shown"),
                            ("answer_submitted", "Answer Submitted"),
                            ("confidence_set", "Confidence Set"),
                            ("lifeline_sent", "Lifeline Sent"),
                            ("host_paused", "Host Paused"),
                            ("host_resumed", "Host Resumed"),
                            ("host_rewound", "Host Rewound"),
                            ("question_branch_selected", "Question Branch Selected"),
                            ("session_ended", "Session Ended"),
                        ],
                        max_length=30,
                    ),
                ),
                ("payload", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sequence_number", models.IntegerField()),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="quiz.room",
                    ),
                ),
            ],
            options={
                "ordering": ["sequence_number"],
                "indexes": [
                    models.Index(
                        fields=["room", "sequence_number"],
                        name="quiz_quizev_room_id_99ad5a_idx",
                    ),
                    models.Index(
                        fields=["room", "event_type"],
                        name="quiz_quizev_room_id_9a99a4_idx",
                    ),
                ],
                "unique_together": {("room", "sequence_number")},
            },
        ),
        migrations.CreateModel(
            name="Score",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("points", models.IntegerField(default=0)),
                ("calibration_score", models.FloatField(default=0.0)),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="quiz.participant",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="quiz.room",
                    ),
                ),
            ],
            options={
                "unique_together": {("participant", "room")},
            },
        ),
    ]
