# Generated by Django 5.2.17 on 2026-08-31 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_participant_user_quiz_creator_score_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="explanation",
            field=models.TextField(
                blank=True,
                default="",
                help_text="AI-generated explanation for the correct answer",
            ),
        ),
    ]
